fieldLayouts:
  8cd49f1e-4086-4c96-a467-06b79288f347:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ade3372b-6797-46c8-9e48-391520de0c3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: ''
            type: craft\fieldlayoutelements\Heading
            uid: d1e525d0-d93f-44ff-bd8d-15ddfb17c3c4
            userCondition: null
          -
            elementCondition: null
            fieldUid: c0eac6e0-b9c1-4794-b000-cfc52e41e069 # Post Id
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29b269b9-93fe-40e8-82dc-8e33bc51e23b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7b6b1a6e-255c-4aa0-b585-d53ac8b89e38 # Post Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f195dd66-75b0-4e48-91ea-fc7f092c8cd4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0c525e9-b10a-4adb-9ad6-188f5c1e0123 # Post Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ba91a7e-b683-4c49-9e4c-b17d8fc1c175
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 189a5629-fb6b-4658-af5a-0af33d6cca72
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 409416f8-7c5e-48ec-84e4-17e8dc02876a # Posts
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
