defaultPlacement: end
fieldLayouts:
  efcff446-761b-4143-9f65-9105fbce9f67:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: women
name: Women
siteSettings:
  37c68312-2895-4e9e-97c5-c63dcf928e36: # craft367
    hasUrls: true
    template: null
    uriFormat: 'women/{slug}'
structure:
  maxLevels: 3
  uid: d2cf747e-9e9a-4e2d-aafe-81c2883f7566
