columnSuffix: smxezgjc
contentColumnType: string(1020)
fieldGroup: 7578fc3a-5bdd-4872-af29-f1fc7dbf253b # Common
handle: homepageContent
instructions: 'This is some instructions'
name: 'Homepage content'
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: '1'
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: 'add some text'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
