columnSuffix: lwnehdyk
contentColumnType: integer(10)
fieldGroup: 213c8386-39fb-4fac-b3f7-beef68e16bde # Post
handle: postId
instructions: null
name: 'Post Id'
searchable: false
settings:
  decimals: 0
  defaultValue: 1
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
